config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # root 'home#index'

  devise_scope :user do
    # ログイン後のリダイレクト先をデフォルトのルートURLから変更したので、新たにログイン画面をルートに設定。
    root 'users/sessions#new'
    # get 'users/index', to: 'users/registrations#index'
    # get 'users/destroy', to: 'users/sessions#destroy'
  end 
  namespace :users do
    get 'dash_boards/index'
  end

  namespace :users do
    # resource :articles
    get 'articles/index'
    get 'articles/show'
    get 'articles/new'
    post 'articles/create'
    get 'articles/edit'
    patch 'articles/update'
    delete 'articles/destroy'
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
  
  validates :name, presence: true

end

app/controllers/users/articles_controller.rb
class Users::ArticlesController < ApplicationController
  before_action :set_articles, only: [:index]
  before_action :set_article_new, only: [:new]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user

  def index
  end

  def show
  end

  def new
  end

  def create
    article = Article.new(article_params)
    if article.save
      flash[:success] = "記事を新規作成しました。"
      redirect_to users_articles_show_path(id: article.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = "内容を更新しました。"
      redirect_to users_articles_show_path(id: @article.id)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:success] = "「記事ID: #{@article.id}」を削除しました。"
    redirect_to users_articles_index_path
  end


  private
    def article_params
      params.require(:article).permit(:title, :content, :image)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/dash_boards_controller.rb
class Users::DashBoardsController < ApplicationController
  before_action :set_user, only: [:index]
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  # end
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users/articles_helper.rb
module Users::ArticlesHelper
end

app/helpers/users/dash_boards_helper.rb
module Users::DashBoardsHelper
end

app/views/users/articles/create.html.erb
<h1>Users::Articles#create</h1>
<p>Find me in app/views/users/articles/create.html.erb</p>

app/views/users/articles/destroy.html.erb
<h1>Users::Articles#destroy</h1>
<p>Find me in app/views/users/articles/destroy.html.erb</p>

app/views/users/articles/edit.html.erb
<div class="container">
  <h2 class="text-center mb-3"><%= I18n.t(".article_edit") %></h2>
  <%= form_with model: @article, url: users_articles_update_path(id: @article.id), method: :patch, local: true do |f| %>
    <div class="field mb-3">
      <label class="form-label-common">タイトル</label>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="field mb-3">
      <label class="form-label-common">内容</label>
      <%= f.text_area :content, rows: 5, class: "form-control" %>
    </div>
    <div class="field mb-3">
      <div><%= f.label :image %></div>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class="text-center"><%= f.submit "更新する", class: "btn btn-md btn-primary" %></div>
  <% end %>
  <div class="mt-3"><%= link_to t('devise.shared.links.back'), :back %></div>
</div>

app/views/users/articles/index.html.erb
<div class="container">
  <h2 class="text-center"><%= I18n.t('.article_index') %></h2>
  <div class="text-center">
    <%= link_to I18n.t('.article_create'), users_articles_new_path, class: "btn dash-boards-button article" %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th class="col-1 vh-center" scope="col">詳細表示</th>
        <th class="col-1 vh-center" scope="col">タイトル</th>
        <th class="col-1 vh-center" scope="col">内容</th>
        <th class="col-2 vh-center" scope="col">画像</th>
        <th class="col-1 vh-center" scope="col">編集・削除</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |art| %>
        <tr>
          <td class="vh-center"><%= link_to "詳細", users_articles_show_path(id: art.id), class: "btn btn-primary" %></td>
          <td class="vh-center"><%= art.title %></td>
          <td class="vh-center"><%= art.content %></td>
          <td class="vh-center">
            <% if art.image.present? %>
              <%= image_tag "#{art.image.thumb.url}" %>
            <% end %>
          </td>
          <td class="vh-center">
            <%= link_to "編集", users_articles_edit_path(id: art.id), class: "btn btn-success" %>
            <%= link_to "削除", users_articles_destroy_path(id: art.id), method: :delete, data: { confirm: "「記事ID: #{art.id}」を削除します。よろしいですか？"}, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="mt-3"><%= link_to '戻る', users_dash_boards_index_path(current_user) %></div>
</div>

app/views/users/articles/new.html.erb
<div class="container">
  <h2 class="text-center mb-3"><%= I18n.t(".article_create") %></h2>
  <%= form_with model: @article, url: users_articles_create_path, local: true do |f| %>
    <div class="field mb-3">
      <label class="form-label-common">タイトル</label>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="field mb-3">
      <label class="form-label-common">内容</label>
      <%= f.text_area :content, rows: 5, class: "form-control" %>
    </div>
    <div class="field mb-3">
      <div><%= f.label :image %></div>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class="text-center"><%= f.submit "新規作成", class: "btn btn-md btn-primary" %></div>
  <% end %>
  <div class="mt-3"><%= link_to t('devise.shared.links.back'), :back %></div>
</div>

app/views/users/articles/show.html.erb
<div class="container">
  <h2 class="text-center"><%= I18n.t('.article_show') %></h2>
  <table class="table">
    <thead>
      <tr>
        <th class="col-1 vh-center" scope="col">タイトル</th>
        <th class="col-1 vh-center" scope="col">内容</th>
        <th class="col-2 vh-center" scope="col">画像</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td class="vh-center"><%= @article.title %></td>
          <td class="vh-center"><%= @article.content %></td>
          <td class="vh-center">
              <%= image_tag "#{@article.image.url}" %>
          </td>
        </tr>
    </tbody>
  </table>
  <div class="vh-center">
    <%= link_to "編集", users_articles_edit_path(id: @article.id), class: "btn btn-success" %>
    <%= link_to "削除", users_articles_destroy_path(id: @article.id), method: :delete, data: { confirm: "「記事ID: #{@article.id}」を削除します。よろしいですか？"}, class: "btn btn-danger" %>
  </div>

  <div class="vh-center mt-3"><%= link_to '記事一覧へ戻る', users_articles_index_path, class: "btn btn-primary" %></div>
</div>

app/views/users/articles/update.html.erb
<h1>Users::Articles#update</h1>
<p>Find me in app/views/users/articles/update.html.erb</p>